// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontFamilies = {
  bold: "Roboto-Bold",
  black: "Roboto-Black",
  boldItalic: "Roboto-BoldItalic",
  blackItalic: "Roboto-BlackItalic",
  medium: "Roboto-Medium",
  mediumItalic: "Roboto-MediumItalic",
  regular: "Roboto-Regular",
  regularItalic: "Roboto-Italic",
  light: "Roboto-Light",
  lightItalic: "Roboto-LightItalic",
}

module.exports = fontFamilies
