// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontSizes = {
 "paragraph": "0.875rem",
 "h6": "1.125rem",
 "h5": "1.25rem",
 "h4": "1.625rem",
 "h3": "2rem",
 "h2": "2.5rem",
 "h1": "3rem",
 "microcopy": "0.75rem",
 "pillText": "0.75rem"
}

module.exports = fontSizes;