// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontFamilies = {
 "bold": "Roboto-Bold",
 "boldItalic": "Roboto-BoldItalic",
 "medium": "Roboto-Medium",
 "mediumItalic": "Roboto-MediumItalic",
 "regular": null,
 "regularItalic": "Roboto-Italic",
 "light": "Roboto-Light",
 "lightItalic": "Roboto-LightItalic"
}

module.exports = fontFamilies;